// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpravceBaterii.Data;

#nullable disable

namespace SpravceBaterii.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250606093339_AddBatteryTypeConstraint")]
    partial class AddBatteryTypeConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SpravceBaterii.Data.Models.Battery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatteryTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ChemicalCompositionId")
                        .HasColumnType("int");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int?>("DisposableBatteryId")
                        .HasColumnType("int");

                    b.Property<int?>("ExpectedLifespan")
                        .HasColumnType("int");

                    b.Property<DateOnly>("InsertionDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsRechargeable")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RechargeableBatteryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BatteryTypeId");

                    b.HasIndex("ChemicalCompositionId");

                    b.HasIndex("DeviceId");

                    b.ToTable("Batteries");
                });

            modelBuilder.Entity("SpravceBaterii.Data.Models.BatteryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("BatteryTypes");
                });

            modelBuilder.Entity("SpravceBaterii.Data.Models.ChargingHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CapacityAfterCharge")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ChargeDate")
                        .HasColumnType("date");

                    b.Property<int>("RechargeableBatteryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RechargeableBatteryId");

                    b.ToTable("ChargingHistories");
                });

            modelBuilder.Entity("SpravceBaterii.Data.Models.ChemicalComposition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ChemicalCompositions");
                });

            modelBuilder.Entity("SpravceBaterii.Data.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatteryCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("SpravceBaterii.Data.Models.DisposableBattery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatteryId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("BatteryId")
                        .IsUnique();

                    b.ToTable("DisposableBatteries");
                });

            modelBuilder.Entity("SpravceBaterii.Data.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Floor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("SpravceBaterii.Data.Models.RechargeableBattery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatteryId")
                        .HasColumnType("int");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<int?>("CycleCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BatteryId")
                        .IsUnique();

                    b.ToTable("RechargeableBatteries");
                });

            modelBuilder.Entity("SpravceBaterii.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SpravceBaterii.Data.Models.Battery", b =>
                {
                    b.HasOne("SpravceBaterii.Data.Models.BatteryType", "BatteryType")
                        .WithMany("Batteries")
                        .HasForeignKey("BatteryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpravceBaterii.Data.Models.ChemicalComposition", "ChemicalComposition")
                        .WithMany("Batteries")
                        .HasForeignKey("ChemicalCompositionId");

                    b.HasOne("SpravceBaterii.Data.Models.Device", "Device")
                        .WithMany("Batteries")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BatteryType");

                    b.Navigation("ChemicalComposition");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("SpravceBaterii.Data.Models.ChargingHistory", b =>
                {
                    b.HasOne("SpravceBaterii.Data.Models.RechargeableBattery", "RechargeableBattery")
                        .WithMany("ChargingHistories")
                        .HasForeignKey("RechargeableBatteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RechargeableBattery");
                });

            modelBuilder.Entity("SpravceBaterii.Data.Models.Device", b =>
                {
                    b.HasOne("SpravceBaterii.Data.Models.Location", "Location")
                        .WithMany("Devices")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("SpravceBaterii.Data.Models.DisposableBattery", b =>
                {
                    b.HasOne("SpravceBaterii.Data.Models.Battery", "Battery")
                        .WithOne("DisposableBattery")
                        .HasForeignKey("SpravceBaterii.Data.Models.DisposableBattery", "BatteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Battery");
                });

            modelBuilder.Entity("SpravceBaterii.Data.Models.Location", b =>
                {
                    b.HasOne("SpravceBaterii.Data.Models.User", "User")
                        .WithMany("Locations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpravceBaterii.Data.Models.RechargeableBattery", b =>
                {
                    b.HasOne("SpravceBaterii.Data.Models.Battery", "Battery")
                        .WithOne("RechargeableBattery")
                        .HasForeignKey("SpravceBaterii.Data.Models.RechargeableBattery", "BatteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Battery");
                });

            modelBuilder.Entity("SpravceBaterii.Data.Models.Battery", b =>
                {
                    b.Navigation("DisposableBattery");

                    b.Navigation("RechargeableBattery");
                });

            modelBuilder.Entity("SpravceBaterii.Data.Models.BatteryType", b =>
                {
                    b.Navigation("Batteries");
                });

            modelBuilder.Entity("SpravceBaterii.Data.Models.ChemicalComposition", b =>
                {
                    b.Navigation("Batteries");
                });

            modelBuilder.Entity("SpravceBaterii.Data.Models.Device", b =>
                {
                    b.Navigation("Batteries");
                });

            modelBuilder.Entity("SpravceBaterii.Data.Models.Location", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("SpravceBaterii.Data.Models.RechargeableBattery", b =>
                {
                    b.Navigation("ChargingHistories");
                });

            modelBuilder.Entity("SpravceBaterii.Data.Models.User", b =>
                {
                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
